<br>
</br>

## Selamat Datang!

Selamat datang di Kursus Mandiri Metasains! Berikut adalah video pengantar dari pemandu kursus. Dalam video ini, pemandu menguraikan tujuan kursus ini didesain dan apa saja yang diharapkan dari peserta kursus.

<center><iframe width="560" height="315" src="https://www.youtube.com/embed/lwlA7v1Ya28" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></center>

<br>
</br>

## Mengenal Sains Terbuka Airlangga

#SainsTerbuka adalah gerakan sosial yang bertujuan untuk mereformasi cara kerja sains tradisional, sekaligus menawarkan konsensus baru untuk mengurangi dampak Krisis Replikasi. #SainsTerbuka juga merupakan strategi untuk mendemokratisasi pengetahuan, sehingga siapapun dapat berpartisipasi dan berkontribusi dalam perkembangan sains.

Sains Terbuka Airlangga adalah sekelompok peneliti pemula yang berasal dari latar belakang keilmuan yang beragam, yang bekerja di Universitas Airlangga. Kami berkomitmen untuk mempromosikan dan mengedukasi peneliti muda dan mahasiswa agar mengadopsi pendekatan Sains Terbuka. Kami percaya bahwa sains (yang baik) seharusnya terbuka, *reproducible*, transparan dan dapat diakses siapa saja. Kami juga percaya bahwa pengetahuan yang dihasilkan saat ini terlalu banyak terkontaminasi oleh penggunaan metrik yang tidak bertanggungjawab, sistem penghargaan, dan kompetisi yang tidak sehat. Kami mengharapkan perubahan ekosistem riset yang menilai kredibilitas temuan riset dengan prinsip kecermatan ilmiah, bukan dengan melihat *outlet* yang menerbitkan temuan tersebut, apalagi *outlet* dengan audiens yang terbatas seperti jurnal ilmiah.


Lebih lanjut silahkan klik: https://sainsterbukaua.github.io/


#### Apa itu sains terbuka (*open science*)? 
* [Wikipedia](https://en.wikipedia.org/wiki/Open_science)
* [UNESCO](http://www.unesco.org/new/en/communication-and-information/portals-and-platforms/goap/open-science-movement/)
* [An introduction to open science (Psychological Science Agenda)](https://www.apa.org/science/about/psa/2019/02/open-science)
* [Open Science Knowledge Base](https://how-to-open.science/)
* Munafò, M. R., Nosek, B. A., Bishop, D. V., Button, K. S., Chambers, C. D., Du Sert, N. P., ... & Ioannidis, J. P. (2017). [A manifesto for reproducible science](http://www.nature.com/articles/s41562-016-0021). Nature Human Behaviour, 1(1), 1-9.

